In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [5]:
dataframe = DataFrame(np.arange(4*4).reshape((4,4)))

In [6]:
dataframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [7]:
blender = np.random.permutation(4)

In [8]:
blender

array([1, 3, 0, 2])

In [9]:
dataframe.take(blender)

0   1   2   3
1   4   5   6   7
3  12  13  14  15
0   0   1   2   3
2   8   9  10  11

In [10]:
# Let imagine a box with 3 marbles in it: labeled 1, 2, and 3
box = np.array([1,2,3])

# Now lets create a random permuation WITH replacement using randint
shaker = np.random.randint(0, len(box), size=10)

In [11]:
shaker

array([1, 1, 0, 0, 0, 0, 0, 0, 2, 2])

In [12]:
g = box.take(shaker)

In [13]:
g

array([2, 2, 1, 1, 1, 1, 1, 1, 3, 3])