In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
#This is random array with normal distribution

A = np.random.randn(5)

In [7]:
A

array([-0.19215812,  1.148392  , -0.09257262,  0.68012694, -0.51392011])

In [8]:
B = np.random.randn(5)

In [9]:
B

array([-0.77790257, -0.69100776, -0.61183532,  0.06435033,  0.75167722])

In [10]:
np.add(A,B)

array([-0.97006069,  0.45738424, -0.70440794,  0.74447726,  0.23775711])

In [11]:
np.maximum(A,B)

array([-0.19215812,  1.148392  , -0.09257262,  0.68012694,  0.75167722])