In [1]:
import numpy as np

In [2]:
5/2

2.5

In [3]:
from __future__ import division

In [6]:
arr1 = np.array([[1,2,3], [4,5,6]])

In [7]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [9]:
arr1/2

array([[ 0.5,  1. ,  1.5],
       [ 2. ,  2.5,  3. ]])

In [10]:
arr1 + 5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr1*arr1

array([[ 1,  4,  9],
       [16, 25, 36]])

In [14]:
1/arr1

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [15]:
arr1/5

array([[ 0.2,  0.4,  0.6],
       [ 0.8,  1. ,  1.2]])